name: Build AppImage

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-appimage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build single-folder with PyInstaller
        run: |
          pyinstaller --noconfirm --clean --onefile --windowed \
            --add-data "assets:assets" \
            --add-data "skins:skins" \
            --add-data "musica:musica" \
            main.py

      - name: Create AppDir
        run: |
          mkdir -p appimage/AppDir/usr/bin
          cp dist/main appimage/AppDir/usr/bin/snake
          mkdir -p appimage/AppDir/usr/share/icons/hicolor/256x256/apps
          # (copiar icono si existe)
          echo '[Desktop Entry]
Name=SnakeUltimate
Exec=snake
Icon=snake
Type=Application
Categories=Game;' > appimage/AppDir/metadata.desktop

      - name: Download appimagetool
        run: |
          wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O appimagetool
          chmod +x appimagetool

      - name: Build AppImage
        run: |
          ./appimagetool appimage/AppDir
      - name: Upload AppImage
        uses: actions/upload-artifact@v3
        with:
          name: snake-appimage
          path: SnakeUltimate-x86_64.AppImage || appimage/*.AppImage
